services:
  bun-dev:
    build:
      context: .
      target: dev
    container_name: bun-dev
    volumes:
      - ./app:/app
    ports:
      - "3333:3333"
    # command: ["bun", "--watch", "server.ts"]
    restart: unless-stopped

