services:
  adonis:
    build: .
    container_name: adonis-hello
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    command: ["bash", "-lc", "bun install && node ace serve --watch"]
    restart: unless-stopped
